self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open("v1").then((cache) => {
      return cache.addAll([
        // Add paths to assets you want to precache here
        "/",
        "/index.html",
        "/main.js",
        // Add more assets here as needed
      ]);
    })
  );
});

// Serve cached assets when offline
self.addEventListener("fetch", (event) => {
  // Ignore changes in .css files generated by Tailwind CSS
  if (event.request.url.includes(".css")) {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
