import productImg from "./assets/Images/demoProduct.jpg";
import productImg2 from "./assets/Images/demoProduct2.jpg";
import productImg3 from "./assets/Images/demoProduct3.jpg";
import productImg4 from "./assets/Images/demoProduct4.jpg";

export const products = {
  products: [
    {
      id: 1,
      name: "almond-toe-court-shoes",
      image: productImg3,
      category: "men-pants",
      price: 99.0,
      stock: 5,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 2,
      name: "Suede Shoes, Blue",
      image: productImg,
      category: "women-tops-tees",
      price: 42.0,
      stock: 4,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 3,
      name: "Leather Driver Saddle Loafers, Tan",
      image: productImg4,
      category: "women-activewear",
      price: 34.0,
      stock: 12,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 4,
      name: "Flip Flops, Red",
      image: productImg,
      category: "men-pants",
      price: 19.0,
      stock: 6,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 5,
      name: "Flip Flops, Blue",
      image: productImg2,
      category: "men-jackets",
      price: 19.0,
      stock: 0,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 6,
      name: "Gold Button Cardigan, Black",
      image: productImg3,
      category: "women-tops-tees",
      price: 167.0,
      stock: 6,
      quantity: 1,
      color: "",
      size: "",
    },
  ],
};
