import productImg from "./assets/Images/demoProduct.jpg";
import productImg2 from "./assets/Images/demoProduct2.jpg";
import productImg3 from "./assets/Images/demoProduct3.jpg";
import productImg4 from "./assets/Images/demoProduct4.jpg";
export const productS = {
  data: [
    {
      id: 7,
      name: "Cotton Shorts, Medium Red",
      image: productImg4,
      category: "men-pants",
      price: 30.0,
      stock: 5,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 8,
      name: "Fine Stripe Short Sleeve￼Shirt, Grey",
      image: productImg,
      category: "men-joggers-sweatpants",
      price: 49.99,
      stock: 9,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 9,
      name: "Fine Stripe Short Sleeve￼Shirt, Green",
      image: productImg3,
      category: "women-activewear",
      price: 49.99,

      stock: 9,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 10,
      name: "Sharkskin Waistcoat, Charcoal",
      image: productImg2,
      category: "women-activewear",
      price: 75.0,
      stock: 2,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 11,
      name: "",
      image: productImg,
      category: "men-tops-tees",
      price: 175.5,
      stock: 1,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 12,
      name: "bird-print-dress-black",
      image: productImg4,
      category: "men-hoodies-sweaters",
      price: 270.0,
      stock: 10,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 13,
      name: "Mid Twist Cut-Out Dress, Pink",
      image: productImg3,
      category: "women-dresses-skirts",
      price: 540.0,
      stock: 5,
      quantity: 1,
      color: "",
      size: "",
    },
    {
      id: 14,
      name: "Gold Button Cardigan, Black",
      image: productImg3,
      category: "women-tops-tees",
      price: 167.0,
      stock: 6,
      quantity: 1,
      color: "",
      size: "",
    },
  ],
};
